//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALER_VW
    {
        public string DEALER_NUM { get; set; }
        public string PARTS_ACCT_NO { get; set; }
        public string DEALERNAME { get; set; }
        public string FCSD_REG_CODE { get; set; }
        public string FCSD_MKT_AREA { get; set; }
        public string FCSD_ZONE { get; set; }
    }
}
