//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_EVENT
    {
        public LBC_EVENT()
        {
            this.LBC_FLIGHT_INFO_DETAILS = new HashSet<LBC_FLIGHT_INFO_DETAILS>();
            this.LBC_REGISTRATION = new HashSet<LBC_REGISTRATION>();
            this.LBC_FLIGHT_INFO = new HashSet<LBC_FLIGHT_INFO>();
            this.LBC_EVENT_SESSION_LOOKUP = new HashSet<LBC_EVENT_SESSION_LOOKUP>();
        }
    
        public decimal EVENT_ID { get; set; }
        public Nullable<decimal> EVENT_YEAR { get; set; }
        public string EVENT_MONTH { get; set; }
        public Nullable<System.DateTime> EVENT_START_DATE { get; set; }
        public Nullable<System.DateTime> EVENT_END_DATE { get; set; }
        public string EVENT_TIME { get; set; }
        public string EVENT_SESSION { get; set; }
        public string EVENT_LOCATION { get; set; }
        public Nullable<decimal> OPEN_LIMIT { get; set; }
        public Nullable<decimal> CURRENT_COUNT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual ICollection<LBC_FLIGHT_INFO_DETAILS> LBC_FLIGHT_INFO_DETAILS { get; set; }
        public virtual ICollection<LBC_REGISTRATION> LBC_REGISTRATION { get; set; }
        public virtual ICollection<LBC_FLIGHT_INFO> LBC_FLIGHT_INFO { get; set; }
        public virtual ICollection<LBC_EVENT_SESSION_LOOKUP> LBC_EVENT_SESSION_LOOKUP { get; set; }
    }
}
