//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_HOTEL_CAR_INFO
    {
        public string STARS_ID { get; set; }
        public decimal EVENT_ID { get; set; }
        public string HOTEL_CONF { get; set; }
        public string HOTEL_NAME { get; set; }
        public Nullable<System.DateTime> HOTEL_CHECK_IN { get; set; }
        public Nullable<System.DateTime> HOTEL_CHECK_OUT { get; set; }
        public string CAR_CONFIRM { get; set; }
        public string ADMIN_NOTES { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CAR_NOTES { get; set; }
    }
}
