//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_CHECKPOINT_COMPLETED
    {
        public string STARS_ID { get; set; }
        public string PA_CODE { get; set; }
        public string TOOL_ORDERED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public decimal CHECKPOINT_ID { get; set; }
        public string EMAIL_ID { get; set; }
        public string SHIPPING_STATUS { get; set; }
    }
}
