//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_SURVEY_REPORT_VW
    {
        public string STARS_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string DLR_NAME { get; set; }
        public string EVENT_SESSION { get; set; }
        public decimal EVENT_ID { get; set; }
        public string EVENT_MONTH { get; set; }
        public Nullable<decimal> EVENT_YEAR { get; set; }
        public decimal SURVEY_ID { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public decimal QUESTION_ID { get; set; }
        public string QUESTION_DESC { get; set; }
        public string Answer { get; set; }
    }
}
