//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_REGISTRATION
    {
        public string STARS_ID { get; set; }
        public string PA_CODE { get; set; }
        public string WSLX_ID { get; set; }
        public decimal EVENT_ID { get; set; }
        public string REGD_STATUS { get; set; }
        public string TRANSPORTATION_MODE { get; set; }
        public string ATTENDED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string NOTES { get; set; }
        public string ADMIN_NOTES { get; set; }
        public string CANCEL_REASON { get; set; }
        public string TRANSPORTATION_NEED { get; set; }
    
        public virtual LBC_EVENT LBC_EVENT { get; set; }
    }
}
