//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_LOGIN_TRACKING
    {
        public decimal SEQ_ID { get; set; }
        public System.DateTime LOGIN_DATE { get; set; }
        public decimal LOGIN_TIME { get; set; }
        public string USERID { get; set; }
        public string ACI { get; set; }
        public string SITE { get; set; }
        public string ORGCODE { get; set; }
        public string EMPCODE { get; set; }
        public string MRROLE { get; set; }
        public string ORG { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
