//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_CHECKPOINT_VW
    {
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string DLR_NAME { get; set; }
        public string DLR_ADDRESS { get; set; }
        public string DLR_CITY { get; set; }
        public string DLR_STATE { get; set; }
        public string DLR_ZIP { get; set; }
        public string DLR_PHONE { get; set; }
        public string SELECT_CONTACT_DLR { get; set; }
        public string Status { get; set; }
        public string TOOL_ORDERED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string EMAIL_ID { get; set; }
        public string SHIPPING_STATUS { get; set; }
        public string STARS_ID { get; set; }
        public string PA_CODE { get; set; }
        public Nullable<decimal> CHECKPOINT_ID { get; set; }
        public Nullable<decimal> CheckPoint1TeamMeetingPDF { get; set; }
        public Nullable<decimal> Checkpoint1SelfStudyPDF { get; set; }
        public Nullable<decimal> Checkpoint1SelfStudyPPTX { get; set; }
        public Nullable<decimal> CheckPoint1TeamMeetingPPTX { get; set; }
    }
}
