//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_INSTITUTION_ENROLL_REPORT
    {
        public string PA_CODE { get; set; }
        public string DEALERSHIP_NAME { get; set; }
        public string SALESCODE { get; set; }
        public string DEALER_TYPE { get; set; }
        public string DUAL_DEALER { get; set; }
        public string DLRC_FIRST_NAME { get; set; }
        public string DLRC_LAST_NAME { get; set; }
        public string DLRC_JOB_TITLE { get; set; }
        public string DLRC_PHONE { get; set; }
        public string DLRC_EMAIL { get; set; }
        public string HOSPITALITY { get; set; }
        public string PROCESS { get; set; }
        public string PRODSKILLS_TRAINING { get; set; }
        public string BRAND_CHAMPION { get; set; }
        public string BC_SALES_FIRST_NAME { get; set; }
        public string BC_SALES_LAST_NAME { get; set; }
        public string BC_SALES_STARSID { get; set; }
        public string BC_SERVICE_FIRST_NAME { get; set; }
        public string BC_SERVICE_LAST_NAME { get; set; }
        public string BC_SERVICE_STARSID { get; set; }
        public string PAY_LUMPSUM { get; set; }
        public string PAY_QUARTERLY { get; set; }
        public string DEALER_AGREE { get; set; }
        public Nullable<System.DateTime> ENROLLMENT_DATE { get; set; }
        public Nullable<decimal> REP_ID { get; set; }
        public Nullable<System.DateTime> STATUS_DATE { get; set; }
        public string DEALER_STATUS { get; set; }
        public Nullable<decimal> UPDATED_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DLRENL_FIRST_NAME { get; set; }
        public string DLRENL_LAST_NAME { get; set; }
        public string DLRENL_PHONE { get; set; }
        public string DLRENL_EMAIL { get; set; }
    }
}
