//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_PROFILE_HISTORY
    {
        public decimal REV_NUM { get; set; }
        public string STARS_ID { get; set; }
        public string PA_CODE { get; set; }
        public string WSLX_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string PHOTO_PATH { get; set; }
        public string PHONE { get; set; }
        public string LBC_CERT { get; set; }
        public string DLR_REGION { get; set; }
        public string DLR_NAME { get; set; }
        public string DLR_ADDRESS { get; set; }
        public string DLR_CITY { get; set; }
        public string DLR_STATE { get; set; }
        public string DLR_ZIP { get; set; }
        public string DLR_PHONE { get; set; }
        public string BIOGRAPHY { get; set; }
        public string SHIRT_SIZE { get; set; }
        public string DIETARY_RESTRICTION { get; set; }
        public string PROFILE_NOTE { get; set; }
        public string PROFILE_TYPE { get; set; }
        public string EMP_STATUS_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string TITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public string ADMIN_NOTES { get; set; }
        public string ZONE { get; set; }
        public string SALESCODE { get; set; }
        public string DEPT_INFO { get; set; }
    }
}
