//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_CHECKPOINT
    {
        public decimal CHECKPOINT_ID { get; set; }
        public string CHK_DESC { get; set; }
        public Nullable<System.DateTime> CHK_START_DATE { get; set; }
        public Nullable<System.DateTime> CHK_END_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string CHK_TITLE { get; set; }
        public string IMAGE_NAME { get; set; }
    }
}
