//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_GUEST_REGISTRATION
    {
        public LBC_GUEST_REGISTRATION()
        {
            this.LBC_GUEST_REGD_SESSION = new HashSet<LBC_GUEST_REGD_SESSION>();
        }
    
        public string WSLX_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string COMPANY_NAME { get; set; }
        public string TITLE { get; set; }
        public string EMAIL_ID { get; set; }
        public string PHONE { get; set; }
        public string DIETARY_RESTRICTION { get; set; }
        public string PROFILE_NOTE { get; set; }
        public string HOTEL_REQUIRED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DEPARTMENT { get; set; }
    
        public virtual ICollection<LBC_GUEST_REGD_SESSION> LBC_GUEST_REGD_SESSION { get; set; }
    }
}
