//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBC_STORY
    {
        public decimal SEQ_ID { get; set; }
        public string STARS_ID { get; set; }
        public string PA_CODE { get; set; }
        public string STORY_TITLE { get; set; }
        public string STORY_CONTENT { get; set; }
        public string IMG_1 { get; set; }
        public string IMG_2 { get; set; }
        public string IMG_3 { get; set; }
        public string STORY_STATUS { get; set; }
        public Nullable<decimal> STORY_RATING { get; set; }
        public Nullable<decimal> STORY_CATEGORY { get; set; }
        public Nullable<decimal> STORY_SUBCATEGORY { get; set; }
        public Nullable<System.DateTime> SUBMISION_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
