//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLK_MFG_CORP
    {
        public string MFG_CORP { get; set; }
        public string MFG_NAME { get; set; }
        public string MFG_DIV { get; set; }
        public string COMMON_FLAG { get; set; }
        public string LUXURY_FLAG { get; set; }
    }
}
