//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION_VE
    {
        public string DIV_CODE { get; set; }
        public string DIV_DESC { get; set; }
        public string REG_CODE { get; set; }
        public string REG_DESC { get; set; }
        public string ZONE { get; set; }
        public string REG_MARKET { get; set; }
    }
}
