//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnBrandChampion.DL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        public string STATE1 { get; set; }
        public string RESTRICTED { get; set; }
        public string DESCRIPTION { get; set; }
        public string ESP_ST_CODE { get; set; }
    }
}
